---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: microservices-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes-manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: microservices-demo
  targetNamespace: default
